/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CourseIdImport } from './routes/$courseId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CourseIdRoute = CourseIdImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$courseId': {
      id: '/$courseId'
      path: '/$courseId'
      fullPath: '/$courseId'
      preLoaderRoute: typeof CourseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$courseId': typeof CourseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$courseId'
  id: '__root__' | '/' | '/$courseId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseIdRoute: typeof CourseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseIdRoute: CourseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$courseId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$courseId": {
      "filePath": "$courseId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
